### ISSUE TITLE
Show All Available Blocks

### ISSUE THREAD

**Issue by techjewel** [getdave/standalone-block-editor#21]
Can you give me some hint, How I can implement "Browse All" blocks into the block inserter?

**Comment by sharukhkhanajm** [comment]
Hey @techjewel  were you able to find this?

**Comment by getdave** [comment]
@techjewel You'll need to add `__experimentalSetIsInserterOpened` to your editor settings. Check out [this PR where I added the exact same functionality to the Navigation Editor](https://github.com/WordPress/gutenberg/pull/34619).

**Comment by techjewel** [comment]
Awesome. Really appriciate it
