### ISSUE TITLE
Custom blocks not showing up on the editor

### ISSUE THREAD

**Issue by anver** [getdave/standalone-block-editor#22]
Hi Dave,

Gr8 work, I'm using this as a starter to build a drag and drop form builder. My plan is to build a outer form wrapper and drag and drop custom components into this wrapper to build the form. The custom components I build shows up on the normal page and post editors but it doesn't show up on my custom editor, any help would be appreciated.

Thx

**Comment by rezaelahidev** [comment]
Is there a solution for this problem?

**Comment by getdave** [comment]
@rezaelahidev I don't have one at the moment. Pull requests are very welcome.

You could also consider https://github.com/Automattic/isolated-block-editor/

**Comment by devfle** [comment]
Hey @rezaelahidev @getdave,

to load custom blocks, you have to set a screen and the is_block_editor property to true. Then all 3rd Party Blocks register correctly. https://developer.wordpress.org/reference/classes/wp_screen/is_block_editor/

**Comment by getdave** [comment]
> Hey @rezaelahidev @getdave,
> 
> to load custom blocks, you have to set a screen and the is_block_editor property to true. Then all 3rd Party Blocks register correctly. https://developer.wordpress.org/reference/classes/wp_screen/is_block_editor/
> 
> Github: https://github.com/WordPress/wordpress-develop/blob/6.0.2/src/wp-admin/includes/class-wp-screen.php#L196

@devfle thank you for this. Would you consider raising a PR to add this functionality by default?

**Comment by devfle** [comment]
@rilwis i will look tomorrow.

**Comment by devfle** [comment]
Created a PR that should fix this issue.
