### ISSUE TITLE
Git clone and npm install problems

### ISSUE THREAD

**Issue by skaTalks** [getdave/standalone-block-editor#48]
Hi, good wishes to you...
I'm newby so be patient please
1) I'd tried to test the project and command `git clone git@github.com:getdave/standalone-block-editor.git` in my plugin dir, but have got the response `Cloning into 'standalone-block-editor'... git@github.com: Permission denied (publickey). fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.` Why, what I do wrong?
2) I'd downloaded Zip from here and tried both Unzip and WP Plugin Install with then `npm install` process tries in both cases. It had failed with so many ERRs that my conscience does not allow me to place them all here.
3) Then I had the third try with `npx @wordpress/create-block standalone-block-editor` and `npm install` process in there. The first `npm install` was the same as in above clause. Second one was successfull after Node re-install. I've reconstruct the standalone-block-editor-demo step by step with tutorial and some `npm install @wordpress/some-package --save`s. It works except one thing, onInput and onChange goes to `Uncaught TypeError: Cannot read properties of undefined (reading 'current'). http://localhost/wp-includes/js/dist/vendor/react-dom.min.js?ver=17.0.1 line 9` and render back an empty screen. I add new blocks, first symbol I input saves in paragraph, I tab them one by one with right Inspector reaction and option changes, but can't input anything else or type URL for an image block etc.
May be I have to do `npm install @wordpress/some-package --save`s for all deps in package.json, may be something else?
4) And one more `wp.components.Popover.Slot name="block-toolbar" is deprecated since version 5.8. Please use wp.blockEditor.BlockTools instead.` What it means? How to resolve it in code?
Thanks for help

**Comment by Rodage** [comment]
Hi, I found that it's missing the ShortcutProvider component.
`import { ShortcutProvider } from '@wordpress/keyboard-shortcuts';
...
		<div className="getdavesbe-block-editor">
			<ShortcutProvider>
				<BlockEditorProvider
					value={ blocks }
					onInput={ handleUpdateBlocks }
					onChange={ handlePersistBlocks }
					settings={ settings }
				>
					<Sidebar.InspectorFill>
						<BlockInspector />
					</Sidebar.InspectorFill>
					<div className="editor-styles-wrapper">
						<BlockEditorKeyboardShortcuts />
						<WritingFlow>
							<ObserveTyping>
								<BlockList className="getdavesbe-block-editor__block-list" />
							</ObserveTyping>
						</WritingFlow>
					</div>
				</BlockEditorProvider>
			</ShortcutProvider>
		</div>`

**Comment by getdave** [comment]
I've updated things in the repo and hopefully this should be resolved. Please feel free to reopen if a fresh clone and `npm i` doesn't resolve things.
