### ISSUE TITLE
build fails on Node v13.11.0

### ISSUE THREAD

**Issue by BramEsposito** [getdave/standalone-block-editor#5]
this appears to be related to [the babel configuration](https://github.com/babel/babel/issues/11216)

I fixed it by upgrading the wordpress scripts to the last version : 9.1.0
Open package.json and change line 20 from:
```"@wordpress/scripts": "^6.2.0",```
to
```"@wordpress/scripts": "^9.1.0",```

Run npm install again

**Comment by getdave** [comment]
Thanks. I have  a branch with all packages upgraded. I will update master asap

**Comment by dbjpanda** [comment]
Same here. Please update!!!! :)

**Comment by getdave** [comment]
I believe all those Issues should now be fixed.

I'd very much welcome/appreciate PRs to resolve such Issues.

I'd recommend following the updated setup process https://github.com/getdave/standalone-block-editor#install-dependencies
