### ISSUE TITLE
Does not work with WordPress 6.1

### ISSUE THREAD

**Issue by techjewel** [getdave/standalone-block-editor#57]
After WordPress 6.1 release the scripts does not work anymore. Can anyone take a look?

**Comment by ManiruzzamanAkash** [comment]
Same problem for `WordPress 6.1`, it doesn't work

It only shows this console warning and no other error/warning. And hope so, this warning is not creating that issue.

<img width="1438" alt="Screenshot 2022-11-30 at 10 43 16 AM" src="https://user-images.githubusercontent.com/17502625/204709486-fa26c22d-5650-4e87-8a89-9e49d7a5552a.png">


It's frustrating. We could fix if there is any error on the console.
